version: 2

sources:
  - name: tpch
    description: Welcome to the dbt Labs demo dbt project! We use the [TPCH dataset](https://docs.snowflake.com/en/user-guide/sample-data-tpch.html) to create a sample project to emulate what a production project might look like!
    database: raw
    schema: TPCH_SF001
    tables:
      - name: orders
        description: single order per customer
        freshness: # make this a warning as this is static data
          warn_after: {count: 6, period: hour}
          # error_after: {count: 12, period: hour}
        loaded_at_field: o_orderdate::timestamp     
        columns:
          - name: o_orderkey
            description: SF*1,500,000 are sparsely populated
            tests: 
              - unique
              - not_null
          - name: o_custkey
            description: Foreign Key to C_CUSTKEY
            tests:
              - relationships:
                  to: source('tpch', 'customer')
                  field: c_custkey
          - name: o_orderstatus
            description: status code of the order
          - name: o_totalprice
            description: raw price
          - name: o_orderdate
            description: date the order was made
          - name: o_orderpriority
            description: code associated with the order
          - name: o_clerk
            description: id of the clerk
          - name: o_shippriority
            description: numeric representation of the shipping priority, zero being the default
          - name: o_comment
            description: 'varchar COMMENT ''VARCHAR(117)'
      - name: customer
        description: Registered cusotmers
        columns:
          - name: c_custkey
            description: unique customer key
            tests:
              - unique:
                  severity: warn
              - not_null:
                  severity: warn
          - name: c_name
            description: customer id
          - name: c_address
            description: address of the customer
          - name: c_nationkey
            description: foreign key to stg_tpch_nations
          - name: c_phone
            description: phone number of the customer
          - name: c_acctbal
            description: raw account balance 
          - name: c_mktsegment
            description: market segment of the customer
          - name: c_comment
            description: 'varchar(79) COMMENT ''VARCHAR(79)'
